image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

skip_non_tags: true

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm i npm@latest -g
  - npm ci

build_script:
  - echo 'no action on regular hook'

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -ne "true") {return}
      npm run build
      # trick for ci recognize DeprecationWarning as error
      if ($LASTEXITCODE -eq 0) {
        $host.SetShouldExit(0)
      }

test: off
